### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by iham** [collective/pas.plugins.ldap#93]
not in the package itself, but when i add it to a project and run even a simple set of tests (are all dependencies loaded and installed)

```
Traceback (most recent call last):
  File "./bin/test", line 352, in <module>
    '--test-path', '/Users/me/myfunnyproject',
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/__init__.py", line 31, in run
    warnings=warnings)
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/__init__.py", line 51, in run_internal
    runner.run()
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/runner.py", line 191, in run
    self.run_tests()
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/runner.py", line 293, in run_tests
    self.skipped, self.import_errors)
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/runner.py", line 462, in run_layer
    import_errors)
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/runner.py", line 385, in run_tests
    test(result)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 304, in run
    result.startTest(self)
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/runner.py", line 846, in startTest
    self.testSetUp()
  File "/Users/me/myfunnyproject/eggs/zope.testrunner-5.0-py2.7.egg/zope/testrunner/runner.py", line 831, in testSetUp
    layer.testSetUp()
  File "/Users/me/myfunnyproject/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/layers.py", line 325, in testSetUp
    self.setUpEnvironment(portal)
  File "/Users/me/myfunnyproject/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/layers.py", line 348, in setUpEnvironment
    helpers.login(portal, TEST_USER_NAME)
  File "/Users/me/myfunnyproject/eggs/plone.app.testing-6.1.3-py2.7.egg/plone/app/testing/helpers.py", line 30, in login
    zope.login(portal['acl_users'], userName)
  File "/Users/me/myfunnyproject/eggs/plone.testing-7.0.3-py2.7.egg/plone/testing/zope.py", line 154, in login
    user = userFolder.getUser(userName)
  File "/Users/me/myfunnyproject/eggs/Products.PluggableAuthService-2.2.1-py2.7.egg/Products/PluggableAuthService/PluggableAuthService.py", line 214, in getUser
    user_info = self._verifyUser(plugins, login=name)
  File "/Users/me/myfunnyproject/eggs/Products.PluggableAuthService-2.2.1-py2.7.egg/Products/PluggableAuthService/PluggableAuthService.py", line 791, in _verifyUser
    info = enumerator.enumerateUsers(**criteria)
  File "/Users/me/myfunnyproject/eggs/pas.plugins.ldap-1.7.0-py2.7.egg/pas/plugins/ldap/plugin.py", line 97, in _wrapper
    logger.exception("Error in {0} -> {1}".format(prefix))
IndexError: tuple index out of range
```

the prefix in question is the string ```users``` which is obviously no tuple.

i also tried deriving from the ldap_fixture in the test but run into a different problem where a directory is not found...

**Comment by macagua** [comment]
@iham In the current version (Plone 6.1.4) on the `main` branch, all unit tests are running successfully with a 100% pass rate
